#!/bin/bash

top=../..

if [ "$#" != "0" ]; then
    echo "Usage: $0"
    exit 1
fi

##==============================================================================
##
## install lsvmtool:
##
##==============================================================================

src=${top}/build/bin/lsvmtool
dest=/sbin/lsvmtool
install -D ${src} ${dest}

if [ "$?" != "0" ]; then
    echo "$0: install failed: ${src} => ${dest}"
    exit 1
fi

##==============================================================================
##
## install lsvmtool-password-agent:
##
##==============================================================================

src=${top}/build/bin/lsvmtool-password-agent
dest=/sbin/lsvmtool-password-agent
install -D ${src} ${dest}
if [ "$?" != "0" ]; then
    echo "$0: install failed: ${src} => ${dest}"
    exit 1
fi

systemd_path=/usr/lib/systemd/system

src=${top}/scripts/lsvmtool-password-agent.path
dest=${systemd_path}/lsvmtool-password-agent.path
install -D ${src} ${dest}
if [ "$?" != "0" ]; then
    echo "$0: install failed: ${src} => ${dest}"
    exit 1
fi

mkdir -p ${systemd_path}/sysinit.target.wants

src=${dest}
dest=${systemd_path}/sysinit.target.wants/lsvmtool-password-agent.path
ln -sfr ${src} ${dest}
if [ "$?" != "0" ]; then
    echo "$0: ln failed: ${src} => ${dest}"
    exit 1
fi

src=${top}/scripts/lsvmtool-password-agent.service
dest=${systemd_path}/lsvmtool-password-agent.service
install -D ${src} ${dest}
if [ "$?" != "0" ]; then
    echo "$0: install failed: ${src} => ${dest}"
    exit 1
fi

##==============================================================================
##
## install module-setup.sh:
##
##==============================================================================

dracut_module=90lsvm
dracut_module_path=/usr/lib/dracut/modules.d/${dracut_module}

src=${top}/scripts/module-setup.sh
dest=${dracut_module_path}/module-setup.sh
install -D ${src} ${dest}
if [ "$?" != "0" ]; then
    echo "$0: install failed: ${src} => ${dest}"
    exit 1
fi
