#! /bin/sh
### BEGIN INIT INFO
# Provides:          lsvmspecialize
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Apply LSVM specializations.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

logfile=/boot/lsvmload/specialize.log
lsvmtool=/sbin/lsvmtool
specialize=/boot/lsvmload/specialize
specialized=/boot/lsvmload/.specialized

case "$1" in
    start)
        mkdir -p /boot/lsvmload
        rm -f ${logfile}

        # Fail if no lsvmtool utility
        if [ ! -x "${lsvmtool}" ]; then
            echo "$0: file not found: ${lsvmtool}" >> ${logfile}
            rm -rf ${specialize}
            exit 1
        fi

        # If already specialized then exit successfully
        if [ -f "${specialized}" ]; then
            echo "$0: already specialized" >> ${logfile}
            rm -rf ${specialize}
            exit 0
        fi

        # Perform specialization.
        ${lsvmtool} specialize ${specialize} >> ${logfile} 2>&1
        if [ "$?" != "0" ]; then
            echo "$0: specialization failed" >> ${logfile}
            rm -rf ${specialize}
            exit 1
        fi

        # Create file to indicate that specialization was performed
        date > ${specialized}

        # Remove the specialize file:
        rm -rf ${specialize}
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 1
        ;;
esac
